#---------------------------------# 
#      environment configuration  # 
#---------------------------------# 
os: WMF 5
version: 0.3.0.{build}
environment:
  PowerShellGalleryApiKey:
    secure: 3fXfDuds8yhTa7WTOLIEhytrpsej9kcP+4rPrgLaFVmIhimmc+FgUVxkR4u468LH
install: 
  - cinst -y pester
  - ps:
      install-windowsfeature hyper-v-powershell
      Get-PackageProvider -name nuget -ForceBootStrap -Force

#---------------------------------# 
#      build configuration        # 
#---------------------------------# 

build: false

#---------------------------------# 
#      test configuration         # 
#---------------------------------# 

test_script:
    - ps: |
        $testResultsFile = ".\TestsResults.xml"
        $res = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru -ExcludeTag Incomplete
        (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
        if ($res.FailedCount -gt 0) { 
            throw "$($res.FailedCount) tests failed."
        }
    
#---------------------------------# 
#      deployment configuration   # 
#---------------------------------# 

# scripts to run before deployment 
deploy_script: 
  - ps: |
      # Creating project artifact
      $buildFolder = $ENV:APPVEYOR_BUILD_FOLDER
      $StagingFolder = Join-Path -Path $buildFolder -ChildPath 'Staging'
      $null = New-Item -Path $StagingFolder -Type directory
      $ModuleFolder = Join-Path -Path $StagingFolder -ChildPath 'LabBuilder'
      $null = New-Item -Path $ModuleFolder -Type directory
      $VersionFolder = Join-Path -Path $ModuleFolder -ChildPath $ENV:APPVEYOR_BUILD_VERSION
      $null = New-Item -Path $VersionFolder -Type directory
      
      # Populate Version Folder
      $null = Copy-Item -Path (Join-Path -Path $buildFolder -ChildPath 'LaBuilder.psd1') -Destination $VersionFolder
      $null = Copy-Item -Path (Join-Path -Path $buildFolder -ChildPath 'LaBuilder.psm1') -Destination $VersionFolder
      $null = Copy-Item -Path (Join-Path -Path $buildFolder -ChildPath 'LICENSE') -Destination $VersionFolder
      $null = Copy-Item -Path (Join-Path -Path $buildFolder -ChildPath 'README.MD') -Destination $VersionFolder
      $null = Copy-Item -Path (Join-Path -Path $buildFolder -ChildPath 'Samples') -Destination $VersionFolder -Recurse
      $null = Copy-Item -Path (Join-Path -Path $buildFolder -ChildPath 'DscLibrary') -Destination $VersionFolder -Recurse

      # Set version number
      $manifest = Join-Path -Path $VersionFolder -ChildPath "LabBuilder.psd1"
      (Get-Content $manifest -Raw).Replace("1.0.0.0", $env:APPVEYOR_BUILD_VERSION) | Out-File $manifest
      
      # Create zip artifact
      $zipFilePath = Join-Path -Path $buildFolder -ChildPath "${env:APPVEYOR_PROJECT_NAME}_${env:APPVEYOR_BUILD_VERSION}.zip"
      $null = Add-Type -assemblyname System.IO.Compression.FileSystem
      [System.IO.Compression.ZipFile]::CreateFromDirectory($StagingFolder, $zipFilePath)
                  
      # Create Publish Script Artifact
      $PublishScriptName = $env:APPVEYOR_PROJECT_NAME + "." + $env:APPVEYOR_BUILD_VERSION + "_publish.ps1"
      $PublishScriptPath = Join-Path -Path $buildFolder -ChildPath $PublishScriptName
      Set-Content -Path $PublishScriptPath -Value "Publish-Module -Name 'LabBuilder' -RequiredVersion ${env:APPVEYOR_BUILD_VERSION} -NuGetApiKey (Read-Host -Prompt 'NuGetApiKey')"
      
      @(
          # You can add other artifacts here
          $zipFilePath,
          $PublishScriptPath
      ) | % { 
          Write-Host "Pushing package $_ as Appveyor artifact"
          Push-AppveyorArtifact $_
      }

      # If this is a build of the Master branch and not a PR push
      # then publish the Module to the PowerShell Gallery.
      if ((! $ENV:APPVEYOR_PULL_REQUEST_NUMBER) -and ($ENV:APPVEYOR_REPO_BRANCH -eq 'master'))
      {
        Write-Host "Publishing Module to PowerShell Gallery"
        Copy-Item -Path $ModuleFolder -Destination ($ENV:PSModulePath -split ';')[0] -Recurse
        Get-PackageProvider -Name NuGet -ForceBootstrap
        Publish-Module -Name 'LabBuilder' -RequiredVersion ${env:APPVEYOR_BUILD_VERSION} -NuGetApiKey $ENV:PowerShellGalleryApiKey -Confirm:$false
      }
      
      # Remove Staging Folder
      $null = Remove-Item -Path $StagingFolder -Recurse -Force

on_finish:
    - ps: Get-ChildItem "$ProjectRoot\LabBuilder\Artifacts\*.*" | Foreach-Object { Push-AppveyorArtifact $_ }
